version: '3.8'

services:
  broker:
    image: eclipse-mosquitto:2
    volumes:
      - mqtt-data:/mosquitto/data
      - ./docker/mosquitto:/mosquitto/config
    ports:
      - 1883:1883
    networks:
      - net
  auth:
    build: auth-service
    networks:
      - net

networks:
  net:

volumes:
  mqtt-data: